language: android
android:
  components:
    - build-tools-28.0.3
    - android-28

matrix:
  include:
    - os: linux
      dist: xenial
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - libgtk-3-dev
    - os: osx
      osx_image: xcode10

script:
  - ./gradlew build
